## I am just trying to learn new things ##

In [1]:
print("Hello ")

Hello 


In [2]:
print(4+6)

10


In [3]:
print("this is very easy calculation")

this is very easy calculation


In [1]:
import numpy as np


In [2]:
li = [1, 2, 3, 4, 5]
arr = np.array(li)
print(arr)

[1 2 3 4 5]


In [3]:
print(li)

[1, 2, 3, 4, 5]


In [4]:
ar = np.array([[1, 2, 3], [4, 5, 6]])
print(ar)

[[1 2 3]
 [4 5 6]]


In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
arr= [[1, 2, 3], [4, 5, 6]]
arr

[[1, 2, 3], [4, 5, 6]]

In [7]:
myarr = np.array(arr)

print(myarr)



NameError: name 'np' is not defined